#!/usr/bin/env python3
"""Generate the pinned ISO/SIX + CLDR currency manifest table.

Reads SIX List One XML and CLDR supplementalData.xml, applies the accepted
155-code fiat candidate exclusions, and writes crates/core/src/money/generated.rs.

VED has no CLDR `from` date (tender=false). valid_from comes from ISO 4217
Amendment 170 (2021-10-01).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import xml.etree.ElementTree as ET
from pathlib import Path

EXCLUDE = {
    "BOV",
    "CHE",
    "CHW",
    "CLF",
    "COU",
    "MXV",
    "USN",
    "UYI",
    "UYW",
    "XAD",
    "XAG",
    "XAU",
    "XPD",
    "XPT",
    "XBA",
    "XBB",
    "XBC",
    "XBD",
    "XDR",
    "XSU",
    "XUA",
    "XTS",
    "XXX",
}

# CLDR 48.2 lists VED as tender=false with no from-date.
VALID_FROM_OVERRIDES = {
    "VED": (2021, 10, 1),
}

EXPECTED_COUNT = 155
SIX_SOURCE_URL = (
    "https://www.six-group.com/dam/download/financial-information/"
    "data-center/iso-currrency/lists/list-one.xml"
)
CLDR_SOURCE_URL = (
    "https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/"
    "common/supplemental/supplementalData.xml"
)
CLDR_VERSION = "48.2"
MANIFEST_VERSION = "1"


def sha256_hex(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_six(path: Path) -> tuple[str, dict[str, dict[str, object]]]:
    root = ET.fromstring(path.read_bytes())
    published = root.attrib.get("Pblshd")
    if not published:
        raise SystemExit("SIX List One is missing Pblshd")
    by_code: dict[str, dict[str, object]] = {}
    for ntry in root.findall(".//CcyNtry"):
        code = ntry.findtext("Ccy")
        if not code or code in EXCLUDE:
            continue
        name = (ntry.findtext("CcyNm") or "").strip()
        numeric = ntry.findtext("CcyNbr")
        digits_raw = (ntry.findtext("CcyMnrUnts") or "").strip()
        if not numeric or digits_raw in ("", "N.A."):
            continue
        parsed = {
            "name": name,
            "numeric": int(numeric),
            "digits": int(digits_raw),
        }
        existing = by_code.get(code)
        if existing is None:
            by_code[code] = parsed
            continue
        if existing["numeric"] != parsed["numeric"] or existing["digits"] != parsed["digits"]:
            raise SystemExit(
                f"inconsistent List One row for {code}: {existing} vs {parsed}"
            )
    return published, by_code


def parse_cldr_from_dates(path: Path) -> dict[str, tuple[int, int, int]]:
    root = ET.fromstring(path.read_bytes())
    currency_data = next(
        el for el in root.iter() if el.tag.split("}")[-1] == "currencyData"
    )
    from_dates: dict[str, tuple[int, int, int]] = {}
    for region in currency_data:
        if region.tag.split("}")[-1] != "region":
            continue
        for currency in region:
            if currency.tag.split("}")[-1] != "currency":
                continue
            code = currency.attrib.get("iso4217")
            start = currency.attrib.get("from")
            if not code or not start:
                continue
            year, month, day = (int(part) for part in start.split("-"))
            value = (year, month, day)
            current = from_dates.get(code)
            if current is None or value < current:
                from_dates[code] = value
    from_dates.update(VALID_FROM_OVERRIDES)
    return from_dates


def render(
    published: str,
    six_digest: str,
    cldr_digest: str,
    rows: list[tuple[str, int, str, int, int, int, int]],
) -> str:
    lines = [
        "// @generated by scripts/generate-currency-manifest.py. Do not edit by hand.",
        f"// SIX List One published {published}; CLDR {CLDR_VERSION} supplemental currency data.",
        "",
        "pub(crate) struct RawCurrency {",
        "    pub code: &'static str,",
        "    pub numeric_code: u16,",
        "    pub name: &'static str,",
        "    pub minor_unit_digits: u8,",
        "    pub valid_from_ymd: (i32, u32, u32),",
        "}",
        "",
        f'pub const MANIFEST_VERSION: &str = "{MANIFEST_VERSION}";',
        f'pub const SIX_PUBLICATION_DATE: &str = "{published}";',
        "pub const SIX_SOURCE_URL: &str =",
        f'    "{SIX_SOURCE_URL}";',
        "pub const SIX_SHA256: &str =",
        f'    "{six_digest}";',
        f'pub const CLDR_VERSION: &str = "{CLDR_VERSION}";',
        "pub const CLDR_SOURCE_URL: &str =",
        f'    "{CLDR_SOURCE_URL}";',
        "pub const CLDR_SHA256: &str =",
        f'    "{cldr_digest}";',
        f"pub const CANDIDATE_COUNT: usize = {EXPECTED_COUNT};",
        "",
        "#[rustfmt::skip]",
        "pub(crate) const RAW_CURRENCIES: &[RawCurrency] = &[",
    ]
    for code, numeric, name, digits, year, month, day in rows:
        name_lit = json.dumps(name, ensure_ascii=False)
        lines.append(
            "    RawCurrency { "
            f'code: "{code}", numeric_code: {numeric}, name: {name_lit}, '
            f"minor_unit_digits: {digits}, valid_from_ymd: ({year}, {month}, {day}) }},"
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--six", required=True, type=Path)
    parser.add_argument("--cldr", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    published, by_code = parse_six(args.six)
    if len(by_code) != EXPECTED_COUNT:
        raise SystemExit(f"expected {EXPECTED_COUNT} codes, got {len(by_code)}")
    from_dates = parse_cldr_from_dates(args.cldr)
    missing = sorted(code for code in by_code if code not in from_dates)
    if missing:
        raise SystemExit(f"missing CLDR/override valid_from: {missing}")

    rows = []
    for code in sorted(by_code):
        record = by_code[code]
        year, month, day = from_dates[code]
        rows.append(
            (
                code,
                int(record["numeric"]),
                str(record["name"]),
                int(record["digits"]),
                year,
                month,
                day,
            )
        )

    args.out.write_text(
        render(published, sha256_hex(args.six), sha256_hex(args.cldr), rows)
    )


if __name__ == "__main__":
    main()
