/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TransactionsIndexImport } from './routes/transactions/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as PortfolioIndexImport } from './routes/portfolio/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as BudgetsIndexImport } from './routes/budgets/index'
import { Route as AccountsIndexImport } from './routes/accounts/index'
import { Route as TransactionsTagsIndexImport } from './routes/transactions/tags/index'
import { Route as TransactionsCategoriesIndexImport } from './routes/transactions/categories/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsIndexRoute = TransactionsIndexImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioIndexRoute = PortfolioIndexImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const BudgetsIndexRoute = BudgetsIndexImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => rootRoute,
} as any)

const AccountsIndexRoute = AccountsIndexImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsTagsIndexRoute = TransactionsTagsIndexImport.update({
  id: '/transactions/tags/',
  path: '/transactions/tags/',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsCategoriesIndexRoute =
  TransactionsCategoriesIndexImport.update({
    id: '/transactions/categories/',
    path: '/transactions/categories/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsIndexImport
      parentRoute: typeof rootRoute
    }
    '/budgets/': {
      id: '/budgets/'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/transactions/categories/': {
      id: '/transactions/categories/'
      path: '/transactions/categories'
      fullPath: '/transactions/categories'
      preLoaderRoute: typeof TransactionsCategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/transactions/tags/': {
      id: '/transactions/tags/'
      path: '/transactions/tags'
      fullPath: '/transactions/tags'
      preLoaderRoute: typeof TransactionsTagsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsIndexRoute
  '/budgets': typeof BudgetsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transactions/categories': typeof TransactionsCategoriesIndexRoute
  '/transactions/tags': typeof TransactionsTagsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsIndexRoute
  '/budgets': typeof BudgetsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transactions/categories': typeof TransactionsCategoriesIndexRoute
  '/transactions/tags': typeof TransactionsTagsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/accounts/': typeof AccountsIndexRoute
  '/budgets/': typeof BudgetsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transactions/categories/': typeof TransactionsCategoriesIndexRoute
  '/transactions/tags/': typeof TransactionsTagsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/dashboard'
    | '/portfolio'
    | '/settings'
    | '/transactions'
    | '/transactions/categories'
    | '/transactions/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/dashboard'
    | '/portfolio'
    | '/settings'
    | '/transactions'
    | '/transactions/categories'
    | '/transactions/tags'
  id:
    | '__root__'
    | '/'
    | '/accounts/'
    | '/budgets/'
    | '/dashboard/'
    | '/portfolio/'
    | '/settings/'
    | '/transactions/'
    | '/transactions/categories/'
    | '/transactions/tags/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  BudgetsIndexRoute: typeof BudgetsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  TransactionsCategoriesIndexRoute: typeof TransactionsCategoriesIndexRoute
  TransactionsTagsIndexRoute: typeof TransactionsTagsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  BudgetsIndexRoute: BudgetsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  TransactionsCategoriesIndexRoute: TransactionsCategoriesIndexRoute,
  TransactionsTagsIndexRoute: TransactionsTagsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accounts/",
        "/budgets/",
        "/dashboard/",
        "/portfolio/",
        "/settings/",
        "/transactions/",
        "/transactions/categories/",
        "/transactions/tags/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/accounts/": {
      "filePath": "accounts/index.tsx"
    },
    "/budgets/": {
      "filePath": "budgets/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/portfolio/": {
      "filePath": "portfolio/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/transactions/": {
      "filePath": "transactions/index.tsx"
    },
    "/transactions/categories/": {
      "filePath": "transactions/categories/index.tsx"
    },
    "/transactions/tags/": {
      "filePath": "transactions/tags/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
