/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CashFlowRouteImport } from './routes/cash-flow'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashFlowIndexRouteImport } from './routes/cash-flow.index'
import { Route as CashFlowTransactionsRouteImport } from './routes/cash-flow.transactions'
import { Route as CashFlowForecastRouteImport } from './routes/cash-flow.forecast'
import { Route as CashFlowCategoriesRouteImport } from './routes/cash-flow.categories'
import { Route as CashFlowBudgetsRouteImport } from './routes/cash-flow.budgets'
import { Route as CashFlowBudgetsIndexRouteImport } from './routes/cash-flow.budgets.index'
import { Route as CashFlowBudgetsBudgetIdRouteImport } from './routes/cash-flow.budgets.$budgetId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowRoute = CashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowIndexRoute = CashFlowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CashFlowRoute,
} as any)
const CashFlowTransactionsRoute = CashFlowTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => CashFlowRoute,
} as any)
const CashFlowForecastRoute = CashFlowForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => CashFlowRoute,
} as any)
const CashFlowCategoriesRoute = CashFlowCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => CashFlowRoute,
} as any)
const CashFlowBudgetsRoute = CashFlowBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => CashFlowRoute,
} as any)
const CashFlowBudgetsIndexRoute = CashFlowBudgetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CashFlowBudgetsRoute,
} as any)
const CashFlowBudgetsBudgetIdRoute = CashFlowBudgetsBudgetIdRouteImport.update({
  id: '/$budgetId',
  path: '/$budgetId',
  getParentRoute: () => CashFlowBudgetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash-flow': typeof CashFlowRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/net-worth': typeof NetWorthRoute
  '/settings': typeof SettingsRoute
  '/cash-flow/budgets': typeof CashFlowBudgetsRouteWithChildren
  '/cash-flow/categories': typeof CashFlowCategoriesRoute
  '/cash-flow/forecast': typeof CashFlowForecastRoute
  '/cash-flow/transactions': typeof CashFlowTransactionsRoute
  '/cash-flow/': typeof CashFlowIndexRoute
  '/cash-flow/budgets/$budgetId': typeof CashFlowBudgetsBudgetIdRoute
  '/cash-flow/budgets/': typeof CashFlowBudgetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/net-worth': typeof NetWorthRoute
  '/settings': typeof SettingsRoute
  '/cash-flow/categories': typeof CashFlowCategoriesRoute
  '/cash-flow/forecast': typeof CashFlowForecastRoute
  '/cash-flow/transactions': typeof CashFlowTransactionsRoute
  '/cash-flow': typeof CashFlowIndexRoute
  '/cash-flow/budgets/$budgetId': typeof CashFlowBudgetsBudgetIdRoute
  '/cash-flow/budgets': typeof CashFlowBudgetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash-flow': typeof CashFlowRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/net-worth': typeof NetWorthRoute
  '/settings': typeof SettingsRoute
  '/cash-flow/budgets': typeof CashFlowBudgetsRouteWithChildren
  '/cash-flow/categories': typeof CashFlowCategoriesRoute
  '/cash-flow/forecast': typeof CashFlowForecastRoute
  '/cash-flow/transactions': typeof CashFlowTransactionsRoute
  '/cash-flow/': typeof CashFlowIndexRoute
  '/cash-flow/budgets/$budgetId': typeof CashFlowBudgetsBudgetIdRoute
  '/cash-flow/budgets/': typeof CashFlowBudgetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash-flow'
    | '/dashboard'
    | '/net-worth'
    | '/settings'
    | '/cash-flow/budgets'
    | '/cash-flow/categories'
    | '/cash-flow/forecast'
    | '/cash-flow/transactions'
    | '/cash-flow/'
    | '/cash-flow/budgets/$budgetId'
    | '/cash-flow/budgets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/net-worth'
    | '/settings'
    | '/cash-flow/categories'
    | '/cash-flow/forecast'
    | '/cash-flow/transactions'
    | '/cash-flow'
    | '/cash-flow/budgets/$budgetId'
    | '/cash-flow/budgets'
  id:
    | '__root__'
    | '/'
    | '/cash-flow'
    | '/dashboard'
    | '/net-worth'
    | '/settings'
    | '/cash-flow/budgets'
    | '/cash-flow/categories'
    | '/cash-flow/forecast'
    | '/cash-flow/transactions'
    | '/cash-flow/'
    | '/cash-flow/budgets/$budgetId'
    | '/cash-flow/budgets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashFlowRoute: typeof CashFlowRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  NetWorthRoute: typeof NetWorthRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow': {
      id: '/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow/': {
      id: '/cash-flow/'
      path: '/'
      fullPath: '/cash-flow/'
      preLoaderRoute: typeof CashFlowIndexRouteImport
      parentRoute: typeof CashFlowRoute
    }
    '/cash-flow/transactions': {
      id: '/cash-flow/transactions'
      path: '/transactions'
      fullPath: '/cash-flow/transactions'
      preLoaderRoute: typeof CashFlowTransactionsRouteImport
      parentRoute: typeof CashFlowRoute
    }
    '/cash-flow/forecast': {
      id: '/cash-flow/forecast'
      path: '/forecast'
      fullPath: '/cash-flow/forecast'
      preLoaderRoute: typeof CashFlowForecastRouteImport
      parentRoute: typeof CashFlowRoute
    }
    '/cash-flow/categories': {
      id: '/cash-flow/categories'
      path: '/categories'
      fullPath: '/cash-flow/categories'
      preLoaderRoute: typeof CashFlowCategoriesRouteImport
      parentRoute: typeof CashFlowRoute
    }
    '/cash-flow/budgets': {
      id: '/cash-flow/budgets'
      path: '/budgets'
      fullPath: '/cash-flow/budgets'
      preLoaderRoute: typeof CashFlowBudgetsRouteImport
      parentRoute: typeof CashFlowRoute
    }
    '/cash-flow/budgets/': {
      id: '/cash-flow/budgets/'
      path: '/'
      fullPath: '/cash-flow/budgets/'
      preLoaderRoute: typeof CashFlowBudgetsIndexRouteImport
      parentRoute: typeof CashFlowBudgetsRoute
    }
    '/cash-flow/budgets/$budgetId': {
      id: '/cash-flow/budgets/$budgetId'
      path: '/$budgetId'
      fullPath: '/cash-flow/budgets/$budgetId'
      preLoaderRoute: typeof CashFlowBudgetsBudgetIdRouteImport
      parentRoute: typeof CashFlowBudgetsRoute
    }
  }
}

interface CashFlowBudgetsRouteChildren {
  CashFlowBudgetsBudgetIdRoute: typeof CashFlowBudgetsBudgetIdRoute
  CashFlowBudgetsIndexRoute: typeof CashFlowBudgetsIndexRoute
}

const CashFlowBudgetsRouteChildren: CashFlowBudgetsRouteChildren = {
  CashFlowBudgetsBudgetIdRoute: CashFlowBudgetsBudgetIdRoute,
  CashFlowBudgetsIndexRoute: CashFlowBudgetsIndexRoute,
}

const CashFlowBudgetsRouteWithChildren = CashFlowBudgetsRoute._addFileChildren(
  CashFlowBudgetsRouteChildren,
)

interface CashFlowRouteChildren {
  CashFlowBudgetsRoute: typeof CashFlowBudgetsRouteWithChildren
  CashFlowCategoriesRoute: typeof CashFlowCategoriesRoute
  CashFlowForecastRoute: typeof CashFlowForecastRoute
  CashFlowTransactionsRoute: typeof CashFlowTransactionsRoute
  CashFlowIndexRoute: typeof CashFlowIndexRoute
}

const CashFlowRouteChildren: CashFlowRouteChildren = {
  CashFlowBudgetsRoute: CashFlowBudgetsRouteWithChildren,
  CashFlowCategoriesRoute: CashFlowCategoriesRoute,
  CashFlowForecastRoute: CashFlowForecastRoute,
  CashFlowTransactionsRoute: CashFlowTransactionsRoute,
  CashFlowIndexRoute: CashFlowIndexRoute,
}

const CashFlowRouteWithChildren = CashFlowRoute._addFileChildren(
  CashFlowRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashFlowRoute: CashFlowRouteWithChildren,
  DashboardRoute: DashboardRoute,
  NetWorthRoute: NetWorthRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
